services:
  app:
    environment:
      - PROJECT_PATH=/project/bun_template
      - TZ=Asia/Taipei
    build:
      context: ..
      target: dev
      # secrets:
      #   - GITHUB_TOKEN
      args:
        - PROJECT_PATH=/project/bun_template
        - TZ=Asia/Taipei
    volumes:
      - ..:/project/bun_template:rw,cached
      - ${BUN_INSTALL_CACHE_DIR:-${HOME}/.bun/install/cache}:/root/.bun/install/cache:rw,z
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]

# secrets:
#   GITHUB_TOKEN:
#     environment: GITHUB_TOKEN
